<?php

namespace App\Models\Admin\Account\Paymentvoucher;

use App\Models\Commontraits\Admin\AdmingeneralTraits;
use App\Models\Miscellaneous\Paymentvoucherhelper;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Paymentvoucher extends Model
{
    use AdmingeneralTraits, SoftDeletes;

    protected $appends = ['paymentvoucher_uniqid', 'paymentvoucher_user', 'paymentvoucher_phone'];

    protected $dates = ['deleted_at'];
    protected $guarded = ['id'];

    protected $casts = [
        'created_at' => 'datetime:d-M-Y h:i:s',
        'updated_at' => 'datetime:d-M-Y h:i:s',
    ];

    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            Paymentvoucherhelper::autogeneratedpaymentid(6, 'PV', $model);
        });
        static::updating(function ($model) {
            Paymentvoucherhelper::autogeneratedpaymentid(false, false, $model);
        });
    }

    public function paymentable()
    {
        return $this->morphTo();
    }

    public function getPaymentvoucherUniqidAttribute()
    {
        if ($this->hms_uniqid) {
            return $this->hms_uniqid;
        } elseif ($this->pharm_uniqid) {
            return $this->pharm_uniqid;
        } elseif ($this->lab_uniqid) {
            return $this->lab_uniqid;
        } elseif ($this->scan_uniqid) {
            return $this->scan_uniqid;
        } elseif ($this->xray_uniqid) {
            return $this->xray_uniqid;
        }
    }

    public function getPaymentvoucherUserAttribute()
    {
        if ($this->payment_to == 1) {
            return $this->paymentable->name . ' (' . $this->paymentable->uhid . ')';
        } elseif ($this->payment_to == 2) {
            return $this->paymentable->name . ' (' . $this->paymentable->uniqid . ')';
        } elseif ($this->payment_to == 3) {
            return $this->paymentable->company_name . ' (' .
            $this->paymentable->uniqid
                . ')';
        } else {
            return $this->others_name;
        }
    }
    public function getPaymentvoucherPhoneAttribute()
    {
        if ($this->payment_to == 1 || $this->payment_to == 2) {
            return $this->paymentable->phone;
        } elseif ($this->payment_to == 3) {
            return $this->paymentable->contact_mobile_no;
        } else {
            return '-';
        }
    }
}
