<?php

namespace App\Models\Miscellaneous;

use App\Models\Miscellaneous\Paymentvoucherhelper;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class Paymentvoucherhelper extends Model
{

    public static function autogeneratedpaymentid($digit, $prefix, $model)
    {
        if ($digit) {
            $uniqueId = Paymentvoucherhelper::getNextSequencepaymentId($digit, $prefix, $model);
            $model->uuid = (string) Str::uuid();
            $model->sys_id = $uniqueId['sys_id'];
            $model->uniqid = $uniqueId['uniqid'];
            $model->sequence_id = $uniqueId['sequence_id'];
            $model->hms_uniqid = $uniqueId['hms_uniqid'] ?? null;
            $model->hms_sequence_id = $uniqueId['hms_sequence_id'] ?? null;
            $model->pharm_uniqid = $uniqueId['pharm_uniqid'] ?? null;
            $model->pharm_sequence_id = $uniqueId['pharm_sequence_id'] ?? null;
            $model->lab_uniqid = $uniqueId['lab_uniqid'] ?? null;
            $model->lab_sequence_id = $uniqueId['lab_sequence_id'] ?? null;
            $model->scan_uniqid = $uniqueId['scan_uniqid'] ?? null;
            $model->scan_sequence_id = $uniqueId['scan_sequence_id'] ?? null;
            $model->xray_uniqid = $uniqueId['xray_uniqid'] ?? null;
            $model->xray_sequence_id = $uniqueId['xray_sequence_id'] ?? null;
        }
    }

    public static function getNextSequencepaymentId($digit, $name, $model)
    {
        $object = $model::withTrashed()
            ->orderBy('sequence_id', 'desc')
            ->first();
        $lastId = (!$object) ? 0 : $object->sequence_id;

        if ($model->payment_to == 1) {
            $paymentsequence = $model->payment_type;
        } else {
            $paymentsequence = '1';
        }

        $year = Carbon::now()->format('y');

        switch ($paymentsequence) {
            case '1':

                $hms_object = $model::withTrashed()
                    ->orderBy('hms_sequence_id', 'desc')
                    ->latest()
                    ->first();

                $now = Carbon::now();

                $hms_lastId = (!$hms_object) ? 0 : $hms_object->hms_sequence_id;

                $year = ($now->month < 4) ? $year - 1 : $year;
                $finacialyearobject = $model::withTrashed()
                    ->whereBetween('created_at', [date(($year) . '-04-01'), date(($year + 1) . '-03-31')])->first();
                $hms_lastId = (!$finacialyearobject) ? 0 : $hms_lastId;

                $arr['hms_uniqid'] = 'ENH/H/PV' . '-' . sprintf('%0' . $digit . 'd', intval($hms_lastId) + 1) . '/' . $year . '-' . $year + 1;
                $arr['hms_sequence_id'] = $hms_lastId + 1;

                break;
            case '2':

                $hms_object = $model::withTrashed()
                    ->orderBy('hms_sequence_id', 'desc')
                    ->latest()
                    ->first();

                $now = Carbon::now();

                $hms_lastId = (!$hms_object) ? 0 : $hms_object->hms_sequence_id;

                $year = ($now->month < 4) ? $year - 1 : $year;
                $finacialyearobject = $model::withTrashed()
                    ->whereBetween('created_at', [date(($year) . '-04-01'), date(($year + 1) . '-03-31')])->first();
                $hms_lastId = (!$finacialyearobject) ? 0 : $hms_lastId;

                $arr['hms_uniqid'] = 'ENH/H/PV' . '-' . sprintf('%0' . $digit . 'd', intval($hms_lastId) + 1) . '/' . $year . '-' . $year + 1;
                $arr['hms_sequence_id'] = $hms_lastId + 1;

                break;
            case '3':

                $hms_object = $model::withTrashed()
                    ->orderBy('hms_sequence_id', 'desc')
                    ->latest()
                    ->first();

                $now = Carbon::now();

                $hms_lastId = (!$hms_object) ? 0 : $hms_object->hms_sequence_id;

                $year = ($now->month < 4) ? $year - 1 : $year;
                $finacialyearobject = $model::withTrashed()
                    ->whereBetween('created_at', [date(($year) . '-04-01'), date(($year + 1) . '-03-31')])->first();
                $hms_lastId = (!$finacialyearobject) ? 0 : $hms_lastId;

                $arr['hms_uniqid'] = 'ENH/H/PV' . '-' . sprintf('%0' . $digit . 'd', intval($hms_lastId) + 1) . '/' . $year . '-' . $year + 1;
                $arr['hms_sequence_id'] = $hms_lastId + 1;

                break;

            case '4':

                $pharm_object = $model::withTrashed()
                    ->orderBy('pharm_sequence_id', 'desc')
                    ->latest()
                    ->first();

                $now = Carbon::now();

                $pharm_lastId = (!$pharm_object) ? 0 : $pharm_object->pharm_sequence_id;

                $year = ($now->month < 4) ? $year - 1 : $year;
                $finacialyearobject = $model::withTrashed()
                    ->whereBetween('created_at', [date(($year) . '-04-01'), date(($year + 1) . '-03-31')])->first();
                $pharm_lastId = (!$finacialyearobject) ? 0 : $pharm_lastId;

                $arr['pharm_uniqid'] = 'ENH/P/PV' . '-' . sprintf('%0' . $digit . 'd', intval($pharm_lastId) + 1) . '/' . $year . '-' . $year + 1;
                $arr['pharm_sequence_id'] = $pharm_lastId + 1;
                break;
            case '5':

                $lab_object = $model::withTrashed()
                    ->orderBy('lab_sequence_id', 'desc')
                    ->latest()
                    ->first();

                $now = Carbon::now();

                $lab_lastId = (!$lab_object) ? 0 : $lab_object->lab_sequence_id;

                $year = ($now->month < 4) ? $year - 1 : $year;
                $finacialyearobject = $model::withTrashed()
                    ->whereBetween('created_at', [date(($year) . '-04-01'), date(($year + 1) . '-03-31')])->first();
                $lab_lastId = (!$finacialyearobject) ? 0 : $lab_lastId;

                $arr['lab_uniqid'] = 'ENH/L/PV' . '-' . sprintf('%0' . $digit . 'd', intval($lab_lastId) + 1) . '/' . $year . '-' . $year + 1;
                $arr['lab_sequence_id'] = $lab_lastId + 1;
                break;

            case '6':

                $scan_object = $model::withTrashed()
                    ->orderBy('scan_sequence_id', 'desc')
                    ->latest()
                    ->first();
                $now = Carbon::now();
                $scan_lastId = (!$scan_object) ? 0 : $scan_object->scan_sequence_id;

                $year = ($now->month < 4) ? $year - 1 : $year;
                $finacialyearobject = $model::withTrashed()
                    ->whereBetween('created_at', [date(($year) . '-04-01'), date(($year + 1) . '-03-31')])->first();
                $scan_lastId = (!$finacialyearobject) ? 0 : $scan_lastId;

                $arr['scan_uniqid'] = 'ENH/S/PV' . '-' . sprintf('%0' . $digit . 'd', intval($scan_lastId) + 1) . '/' . $year . '-' . $year + 1;
                $arr['scan_sequence_id'] = $scan_lastId + 1;
                break;

            case '7':

                $xray_object = $model::withTrashed()
                    ->orderBy('xray_sequence_id', 'desc')
                    ->latest()
                    ->first();

                $now = Carbon::now();

                $xray_lastId = (!$xray_object) ? 0 : $xray_object->xray_sequence_id;

                $year = ($now->month < 4) ? $year - 1 : $year;
                $finacialyearobject = $model::withTrashed()
                    ->whereBetween('created_at', [date(($year) . '-04-01'), date(($year + 1) . '-03-31')])->first();
                $xray_lastId = (!$finacialyearobject) ? 0 : $xray_lastId;

                $arr['xray_uniqid'] = 'ENH/X/PV' . '-' . sprintf('%0' . $digit . 'd', intval($xray_lastId) + 1) . '/' . $year . '-' . $year + 1;
                $arr['xray_sequence_id'] = $xray_lastId + 1;
                break;

            default:
                Log::info("Unknown Payment Voucher sequence");
                Log::info("Payment Voucher" . $model);
                break;
        }

        $arr['uniqid'] = 'ENH-' . $name . '-' . sprintf('%0' . $digit . 'd', intval($lastId) + 1) . '/' . $year . '-' . $year + 1;
        $arr['sequence_id'] = $lastId + 1;
        $arr['sys_id'] = md5(uniqid(rand(), true));
        return $arr;
    }
}
