<?php

namespace App\Models\Admin\Billing\Receipt;

use App\Models\Commontraits\Admin\AdmingeneralTraits;
use App\Models\Miscellaneous\Receipthelper;
use App\Models\Patient\Auth\Patient;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Receipt extends Model
{
    use AdmingeneralTraits, SoftDeletes;

    protected $appends = ['receipt_uniqid'];

    protected $dates = ['deleted_at'];
    protected $guarded = ['id'];

    protected $casts = [
        'created_at' => 'datetime:d-M-Y h:i:s',
        'updated_at' => 'datetime:d-M-Y h:i:s',
    ];

    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            Receipthelper::autogeneratedreceiptid(6, 'R', $model);
        });
        static::updating(function ($model) {
            Receipthelper::autogeneratedreceiptid(false, false, $model);
        });
    }

    public function getReceiptUniqidAttribute()
    {
        if ($this->hms_uniqid) {
            return $this->hms_uniqid;
        } elseif ($this->pharm_uniqid) {
            return $this->pharm_uniqid;
        } elseif ($this->lab_uniqid) {
            return $this->lab_uniqid;
        } elseif ($this->scan_uniqid) {
            return $this->scan_uniqid;
        } elseif ($this->xray_uniqid) {
            return $this->xray_uniqid;
        }
    }

    public function patient()
    {
        return $this->belongsTo(Patient::class);
    }

    public function receiptable()
    {
        return $this->morphTo();
    }
}
